name: ProvidentSampleApp
schemes:
  App:
    build:
      targets:
        App: all
options:
  bundleIdPrefix: uk.co.cerihughes
targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      INFOPLIST_FILE: Resources/Info.plist
      DEVELOPMENT_TEAM: Y56955G4Q8
    sources:
      - Source
      - Resources
    dependencies:
      - carthage: Provident
      - carthage: SnapKit