name: SampleApp
schemes:
  App:
    build:
      targets:
        App: all
options:
  bundleIdPrefix: uk.co.cerihughes
projectReferences:
  Provident:
    path: ../Provident.xcodeproj
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.0
targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      INFOPLIST_FILE: Resources/Info.plist
      DEVELOPMENT_TEAM: Y56955G4Q8
    sources:
      - Source
      - Resources
    dependencies:
      - target: Provident/Provident
      - package: SnapKit
