name: SampleApp
schemes:
  SampleApp:
    build:
      targets:
        SampleApp: all
options:
  bundleIdPrefix: uk.co.cerihughes
projectReferences:
  Provident:
    path: ../Provident.xcodeproj
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.0.0
targets:
  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      INFOPLIST_FILE: SampleApp/Info.plist
    sources:
      - SampleApp
    dependencies:
      - target: Provident/Provident
      - package: SnapKit
