name: Test Xcode 14.2 iOS 16.2

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        xcode: [14.3.1, 15.0.1]
        sdk: [iphonesimulator, macosx, appletvsimulator]
        include:
          - name: "Any iOS Device"
            sdk: iphonesimulator
          - name: "Any Mac"
            sdk: macosx
          - name: "Any tvOS Device"
            sdk: appletvsimulator
          - os: 16.4
            xcode: 14.3.1
          - os: 17.0.1
            xcode: 15.0.1
          - os: 13.4
            sdk: macosx
            xcode: 14.3.1
          - os: 14.0
            sdk: macosx
            xcode: 15.0.1

    runs-on: macos-13

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app

      # Install dependencies
      - run: brew install swiftlint xcodegen || true
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: brew outdated xcodegen || brew upgrade xcodegen

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build and test
      - run: set -o pipefail
      - run: mkdir build
      - run: xcodegen
      - run: xcodebuild clean test -project Provident.xcodeproj -scheme Provident -resultBundlePath coverage.xcresult -destination "OS=${{ matrix.os }},name=${{ matrix.name }}" -sdk ${{ matrix.sdk }} CODE_SIGNING_REQUIRED=NO
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
            xcode: true
            xcode_archive_path: ${{ github.workspace }}/coverage.xcresult
