name: Build and test PRs

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_12.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # Install dependencies
      - run: brew install swiftlint || true
      - run: brew outdated swiftlint || brew upgrade swiftlint

      # Checkout
      - uses: actions/checkout@v2
      - run: mkdir build

      # Build and test
      - run: set -o pipefail
      - run: xcodebuild clean test -scheme Provident -destination "OS=latest,name=iPhone 11" -destination "OS=latest,name=iPad (8th generation)" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Codecov
        uses: codecov/codecov-action@v1.0.6