name: Build and test PRs

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Install dependencies
      - run: brew install swiftlint || true
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: set -o pipefail

      # Checkout
      - uses: actions/checkout@v2
      - run: mkdir build

      # Build and test (latest)
      - run: sudo xcode-select -switch /Applications/Xcode_12.app
      - run: xcodebuild clean test -project Provident.xcodeproj -scheme Provident -destination "OS=14.0,name=iPhone11" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Codecov
        uses: codecov/codecov-action@v1.0.6

      # Build SPM
      - run: swift package generate-xcodeproj --output ProvidentSPM.xcodeproj
      - run: xcodebuild clean build -project ProvidentSPM.xcodeproj -scheme Provident-Package -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

      # Build and test (iOS13)
      - run: sudo xcode-select -switch /Applications/Xcode_11.7.app
      - run: xcodebuild clean test -project Provident.xcodeproj -scheme Provident -destination "OS=13.7,name=iPhone11" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      
      # Build and test (iOS12)
      - run: sudo xcode-select -switch /Applications/Xcode_10.3.app
      - run: xcodebuild clean test -project Provident.xcodeproj -scheme Provident -destination "OS=12.4,name=iPhone11" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO