name: Build SPM

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-11

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_13.2.app

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build SPM
      - run: swift test
      - run: swift package generate-xcodeproj --output ProvidentSPM.xcodeproj
      - run: xcodebuild clean build -project ProvidentSPM.xcodeproj -scheme Provident-Package -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
